const PLAYER_SIZE = 10 / 2000;
const PLAYER_RADIUS = 5 / 700;
const PLAYER_COLOR = '#183c3d';

const BACKGROUND_COLOR = '#eeeefe';
const PLAYER_ACCELERATION = 0.2;
const FIELD_COLOR = 'rgba(238, 238, 254, 0.8)';
const FONT_COLOR = '#937cdd';
const CANVAS_SCALE = 55;
let X_REVIEW = 3800;
let Y_REVIEW = 1840;
const RESIZE_COEF = 0.505;
export {
    PLAYER_SIZE,
    PLAYER_RADIUS,
    PLAYER_COLOR,
    BACKGROUND_COLOR,
    PLAYER_ACCELERATION,
    FIELD_COLOR,
    FONT_COLOR,
    CANVAS_SCALE,
    X_REVIEW,
    Y_REVIEW,
    RESIZE_COEF
}