'use strict';
const MAX_FOOD_NUMBER = 40;
const SMALL_BALL_SIZE = 7 / 2000;
const SMALL_BALL_RADIUS = 2 / 700;

const PLAYER_SIZE = 10 / 2000;
const PLAYER_RADIUS = 5 / 700;
const PLAYER_ACCELERATION = 0.09;

const CONVERGENCE_RADIUS = 1 / 25;

const MAX_ENEMY_NUMBER = 6;
const ENEMY_SIZE = 11 / 2000;
const ENEMY_RADIUS = 5 / 700;
const ENEMY_ACCELERATION = 0.01;

const LOW_ACCELERATION = 0.0045;
const FIELD_COLOR = 'rgba(238, 238, 254, 0.8)';
const FONT_COLOR = '#937cdd';
const CANVAS_SCALE = 55;
let X_REVIEW = 3800;
let Y_REVIEW = 1840;
const RESIZE_COEF = 0.505;
export {
  MAX_FOOD_NUMBER,
  SMALL_BALL_SIZE,
  SMALL_BALL_RADIUS,
  PLAYER_SIZE,
  PLAYER_RADIUS,
  PLAYER_ACCELERATION,
  CONVERGENCE_RADIUS,
  MAX_ENEMY_NUMBER,
  ENEMY_SIZE,
  ENEMY_RADIUS,
  ENEMY_ACCELERATION,
  LOW_ACCELERATION,
  FIELD_COLOR,
  FONT_COLOR,
  CANVAS_SCALE,
  X_REVIEW,
  Y_REVIEW,
  RESIZE_COEF
}